#!/usr/bin/env python3
"""Generate ios_dispatch.c from ios_bridge.h.

The application links both engines. Each one carries its own copy of the bridge,
exported under a prefix (SP_IOSBridge_SetCvar, MP_IOSBridge_SetCvar, ...), because
the bridge talks to engine functions that are hidden when the two are collapsed
into separate objects -- see ios/cmake/Engine.cmake.

The launcher calls the plain names. This file defines them and forwards to
whichever game is active, so the Swift side never has to know there are two.

Run with --check to verify the committed copy is current.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, '..', 'Sources', 'ios_bridge.h')
OUTPUT = os.path.join(HERE, '..', 'Sources', 'ios_dispatch.c')

# Calls that go to both engines instead of to the active one.
#
# These three write the launcher's own settings table, and that table is not the
# running game's -- it is the player's one set of settings, which both copies of
# the bridge have to be holding when either of them writes ios_launcher.cfg.
# Forwarded to the active engine alone the two tables drift: each one seeds
# itself from the file at a different moment, so a setting dropped from one
# (IOSBridge_ForgetCvar) walks straight back in the next time the other writes
# the file. cg_drawCrosshair did exactly that -- seeded once, forgotten by the
# campaign copy, written back by the multiplayer copy, and re-applied over the
# player's own choice on every launch afterwards.
#
# Only void calls can be mirrored, and only ones with no return value to
# disagree about; the generator checks.
MIRRORED = frozenset((
    'IOSBridge_SetCvar',
    'IOSBridge_ForgetCvar',
    'IOSBridge_SetBinding',
))

# One declaration per line in the header, which is the style it is written in.
DECL = re.compile(
    r'^\s*(?P<ret>(?:const\s+)?[A-Za-z_][A-Za-z0-9_]*\s*\**)\s*'
    r'(?P<name>(?:IOSBridge_|Sys_IOS_Launcher)[A-Za-z0-9_]+)\s*'
    r'\((?P<args>[^)]*)\)\s*;',
    re.M)


def parse_args(text):
    """Split an argument list into (type, name) pairs."""
    text = text.strip()
    if text in ('', 'void'):
        return []
    out = []
    for i, part in enumerate(text.split(',')):
        part = part.strip()
        m = re.match(r'^(?P<type>.+?)(?P<name>[A-Za-z_][A-Za-z0-9_]*)$', part)
        if not m:
            # Unnamed argument: give it one, since the forward needs to pass it.
            out.append((part, 'a%d' % i))
            continue
        out.append((m.group('type').strip(), m.group('name')))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()

    text = open(HEADER, encoding='utf-8').read()

    lines = [
        '/*',
        '===========================================================================',
        'Copyright (C) 1999-2005 Id Software, Inc.',
        '',
        'This file is part of Quake III Arena source code.',
        '',
        'Quake III Arena source code is free software; you can redistribute it',
        'and/or modify it under the terms of the GNU General Public License as',
        'published by the Free Software Foundation; either version 2 of the License,',
        'or (at your option) any later version.',
        '',
        'Quake III Arena source code is distributed in the hope that it will be',
        'useful, but WITHOUT ANY WARRANTY; without even the implied warranty of',
        'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the',
        'GNU General Public License for more details.',
        '',
        'You should have received a copy of the GNU General Public License',
        'along with Quake III Arena source code; if not, write to the Free Software',
        'Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA',
        '===========================================================================',
        '*/',
        '// ios_dispatch.c -- GENERATED by ios/cmake/gen_dispatch.py. Do not edit.',
        '//',
        '// The application carries both engines. They are two copies of the same',
        '// code, so each is collapsed into its own object with every symbol made',
        '// local except one entry point and its copy of the bridge, exported under a',
        '// prefix (see ios/cmake/Engine.cmake).',
        '//',
        '// The launcher calls the plain IOSBridge_* names. They are defined here and',
        '// forward to whichever game is running, so the Swift side never sees that',
        '// there are two of everything.',
        '//',
        '// Before a game is chosen, calls go to the campaign engine. That is a real',
        '// answer rather than a placeholder: everything the launcher asks for at that',
        '// point -- where the data folder is, what is in it, what the stored settings',
        '// say -- is read from files both copies read the same way.',
        '//',
        '// The three calls that write the launcher\'s settings go to both instead. The',
        '// settings are the player\'s, not the running game\'s, and whichever copy ends',
        '// up writing ios_launcher.cfg has to be holding all of them.',
        '',
        '#include "ios_bridge.h"',
        '#include "ios_dispatch.h"',
        '',
        'static int iortcwActiveGame = IORTCW_GAME_CAMPAIGN;',
        '',
        'void IOSDispatch_SetGame( int game )',
        '{',
        '\tiortcwActiveGame = game;',
        '}',
        '',
        'int IOSDispatch_Game( void )',
        '{',
        '\treturn iortcwActiveGame;',
        '}',
        '',
    ]

    decls = list(DECL.finditer(text))
    if not decls:
        sys.exit('no declarations found in %s' % HEADER)

    # Forward declarations of both copies.
    lines.append('// The two copies, as exported by each engine object.')
    for m in decls:
        ret, name, arglist = m.group('ret').strip(), m.group('name'), m.group('args')
        for prefix in ('SP', 'MP'):
            lines.append('%s %s_%s( %s );' % (ret, prefix, name, arglist.strip() or 'void'))
    lines.append('')

    # The forwarding definitions.
    for m in decls:
        ret = m.group('ret').strip()
        name = m.group('name')
        arglist = m.group('args')
        params = parse_args(arglist)

        sig = ', '.join('%s%s' % (t if t.endswith('*') else t + ' ', n)
                        for t, n in params) or 'void'
        call = ', '.join(n for _, n in params)

        lines.append('%s %s( %s )' % (ret, name, sig))
        lines.append('{')
        ret_kw = '' if ret == 'void' else 'return '

        if name in MIRRORED:
            if ret != 'void':
                sys.exit('%s returns %s and cannot be mirrored' % (name, ret))
            # Both, in a fixed order, because the two tables are one set of
            # settings held twice. See MIRRORED.
            lines.append('\t// Both copies: this writes the launcher\'s settings,')
            lines.append('\t// which belong to the player and not to a game.')
            lines.append('\tSP_%s( %s );' % (name, call))
            lines.append('\tMP_%s( %s );' % (name, call))
            lines.append('}')
            lines.append('')
            continue

        lines.append('\tif ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {')
        lines.append('\t\t%sMP_%s( %s );' % (ret_kw, name, call))
        if ret == 'void':
            # Without this a void call falls through and runs both copies.
            lines.append('\t\treturn;')
        lines.append('\t}')
        lines.append('')
        lines.append('\t%sSP_%s( %s );' % (ret_kw, name, call))
        lines.append('}')
        lines.append('')

    out = '\n'.join(lines)

    if args.check:
        current = open(OUTPUT, encoding='utf-8').read() if os.path.exists(OUTPUT) else ''
        if current != out:
            sys.exit('%s is stale; rerun gen_dispatch.py' % OUTPUT)
        print('up to date (%d functions)' % len(decls))
        return

    open(OUTPUT, 'w', encoding='utf-8').write(out)
    print('wrote %s (%d functions)' % (OUTPUT, len(decls)))


if __name__ == '__main__':
    main()
