/*
===========================================================================
Copyright (C) 1999-2005 Id Software, Inc.

This file is part of Quake III Arena source code.

Quake III Arena source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

Quake III Arena source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Quake III Arena source code; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
===========================================================================
*/
// ios_dispatch.c -- GENERATED by ios/cmake/gen_dispatch.py. Do not edit.
//
// The application carries both engines. They are two copies of the same
// code, so each is collapsed into its own object with every symbol made
// local except one entry point and its copy of the bridge, exported under a
// prefix (see ios/cmake/Engine.cmake).
//
// The launcher calls the plain IOSBridge_* names. They are defined here and
// forward to whichever game is running, so the Swift side never sees that
// there are two of everything.
//
// Before a game is chosen, calls go to the campaign engine. That is a real
// answer rather than a placeholder: everything the launcher asks for at that
// point -- where the data folder is, what is in it, what the stored settings
// say -- is read from files both copies read the same way.

#include "ios_bridge.h"
#include "ios_dispatch.h"

static int iortcwActiveGame = IORTCW_GAME_CAMPAIGN;

void IOSDispatch_SetGame( int game )
{
	iortcwActiveGame = game;
}

int IOSDispatch_Game( void )
{
	return iortcwActiveGame;
}

// The two copies, as exported by each engine object.
const char * SP_IOSBridge_DataPath( void );
const char * MP_IOSBridge_DataPath( void );
bool SP_IOSBridge_HasGameData( void );
bool MP_IOSBridge_HasGameData( void );
int SP_IOSBridge_GameDataMask( void );
int MP_IOSBridge_GameDataMask( void );
int SP_IOSBridge_ImportLooseData( void );
int MP_IOSBridge_ImportLooseData( void );
int SP_IOSBridge_CampaignModCount( void );
int MP_IOSBridge_CampaignModCount( void );
const char * SP_IOSBridge_CampaignModDir( int index );
const char * MP_IOSBridge_CampaignModDir( int index );
const char * SP_IOSBridge_CampaignModPak( int index );
const char * MP_IOSBridge_CampaignModPak( int index );
bool SP_IOSBridge_CampaignModInstalled( int index );
bool MP_IOSBridge_CampaignModInstalled( int index );
int SP_IOSBridge_CampaignModMaps( int index );
int MP_IOSBridge_CampaignModMaps( int index );
double SP_IOSBridge_CampaignModMegabytes( int index );
double MP_IOSBridge_CampaignModMegabytes( int index );
bool SP_IOSBridge_IsCampaignModDir( const char *dir );
bool MP_IOSBridge_IsCampaignModDir( const char *dir );
bool SP_IOSBridge_RussianPaksPresent( void );
bool MP_IOSBridge_RussianPaksPresent( void );
bool SP_IOSBridge_RussianPaksEnabled( void );
bool MP_IOSBridge_RussianPaksEnabled( void );
int SP_IOSBridge_SetRussianPaks( bool on );
int MP_IOSBridge_SetRussianPaks( bool on );
void SP_IOSBridge_SetCvar( const char *name, const char *value );
void MP_IOSBridge_SetCvar( const char *name, const char *value );
const char * SP_IOSBridge_GetCvar( const char *name );
const char * MP_IOSBridge_GetCvar( const char *name );
void SP_IOSBridge_ForgetCvar( const char *name );
void MP_IOSBridge_ForgetCvar( const char *name );
void SP_IOSBridge_SetBinding( const char *keyName, const char *action );
void MP_IOSBridge_SetBinding( const char *keyName, const char *action );
const char * SP_IOSBridge_GetBinding( const char *keyName );
const char * MP_IOSBridge_GetBinding( const char *keyName );
void SP_IOSBridge_WriteConfig( void );
void MP_IOSBridge_WriteConfig( void );
void SP_IOSBridge_SetStartupCommand( const char *command );
void MP_IOSBridge_SetStartupCommand( const char *command );
void SP_IOSBridge_RotateLog( const char *tag );
void MP_IOSBridge_RotateLog( const char *tag );
const char * SP_IOSBridge_BuildCommandLine( void );
const char * MP_IOSBridge_BuildCommandLine( void );
void SP_IOSBridge_SetExtraArgs( const char *args );
void MP_IOSBridge_SetExtraArgs( const char *args );
bool SP_IOSBridge_IsMultiplayer( void );
bool MP_IOSBridge_IsMultiplayer( void );
void SP_IOSBridge_InitPaths( void );
void MP_IOSBridge_InitPaths( void );
void SP_IOSBridge_InitAudioSession( void );
void MP_IOSBridge_InitAudioSession( void );
void SP_IOSBridge_InitSDLHints( void );
void MP_IOSBridge_InitSDLHints( void );
void SP_IOSBridge_LogAppend( const char *msg );
void MP_IOSBridge_LogAppend( const char *msg );
int SP_IOSBridge_LogSnapshot( char *out, int outSize );
int MP_IOSBridge_LogSnapshot( char *out, int outSize );
unsigned SP_IOSBridge_LogVersion( void );
unsigned MP_IOSBridge_LogVersion( void );
void SP_IOSBridge_SelfTestBegin( const char *title );
void MP_IOSBridge_SelfTestBegin( const char *title );
void SP_IOSBridge_SelfTestRow( int verdict, const char *group, const char *name, const char *detail );
void MP_IOSBridge_SelfTestRow( int verdict, const char *group, const char *name, const char *detail );
void SP_IOSBridge_SelfTestEnd( int passed, int failed, int skipped );
void MP_IOSBridge_SelfTestEnd( int passed, int failed, int skipped );
int SP_IOSBridge_SelfTestSnapshot( char *out, int outSize );
int MP_IOSBridge_SelfTestSnapshot( char *out, int outSize );
int SP_IOSBridge_SelfTestRunning( void );
int MP_IOSBridge_SelfTestRunning( void );
unsigned SP_IOSBridge_SelfTestVersion( void );
unsigned MP_IOSBridge_SelfTestVersion( void );
void SP_IOSBridge_SelfTestCounts( int *passed, int *failed, int *skipped );
void MP_IOSBridge_SelfTestCounts( int *passed, int *failed, int *skipped );
void SP_IOSBridge_SelfTestTitle( char *out, int outSize );
void MP_IOSBridge_SelfTestTitle( char *out, int outSize );
int SP_IOSBridge_SelfTestLoadStored( char *out, int outSize );
int MP_IOSBridge_SelfTestLoadStored( char *out, int outSize );
void SP_IOSBridge_ExecCommand( const char *command );
void MP_IOSBridge_ExecCommand( const char *command );
bool SP_IOSBridge_ServerRunning( void );
bool MP_IOSBridge_ServerRunning( void );
void SP_IOSBridge_SetKeepAwake( bool on );
void MP_IOSBridge_SetKeepAwake( bool on );
bool SP_IOSBridge_IsKeepAwake( void );
bool MP_IOSBridge_IsKeepAwake( void );
bool SP_IOSBridge_ScanData( bool rescan );
bool MP_IOSBridge_ScanData( bool rescan );
int SP_IOSBridge_DataMaps( void );
int MP_IOSBridge_DataMaps( void );
int SP_IOSBridge_DataFiles( void );
int MP_IOSBridge_DataFiles( void );
double SP_IOSBridge_DataMegabytes( void );
double MP_IOSBridge_DataMegabytes( void );
int SP_IOSBridge_SetFileCount( int set );
int MP_IOSBridge_SetFileCount( int set );
const char * SP_IOSBridge_SetFileName( int set, int index );
const char * MP_IOSBridge_SetFileName( int set, int index );
bool SP_IOSBridge_SetFilePresent( int set, int index );
bool MP_IOSBridge_SetFilePresent( int set, int index );
bool SP_IOSBridge_SetFileRequired( int set, int index );
bool MP_IOSBridge_SetFileRequired( int set, int index );
int SP_IOSBridge_SetMaps( int set );
int MP_IOSBridge_SetMaps( int set );
int SP_IOSBridge_SetFiles( int set );
int MP_IOSBridge_SetFiles( int set );
double SP_IOSBridge_SetMegabytes( int set );
double MP_IOSBridge_SetMegabytes( int set );
bool SP_IOSBridge_SetIsPlayable( int set );
bool MP_IOSBridge_SetIsPlayable( int set );
bool SP_IOSBridge_SetIsRecommended( int set );
bool MP_IOSBridge_SetIsRecommended( int set );
const char * SP_IOSBridge_EngineVersion( void );
const char * MP_IOSBridge_EngineVersion( void );
void SP_IOSBridge_LauncherFinished( void );
void MP_IOSBridge_LauncherFinished( void );
bool SP_Sys_IOS_LauncherIsFinished( void );
bool MP_Sys_IOS_LauncherIsFinished( void );
void SP_Sys_IOS_LauncherReset( void );
void MP_Sys_IOS_LauncherReset( void );

const char * IOSBridge_DataPath( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_DataPath(  );
	}

	return SP_IOSBridge_DataPath(  );
}

bool IOSBridge_HasGameData( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_HasGameData(  );
	}

	return SP_IOSBridge_HasGameData(  );
}

int IOSBridge_GameDataMask( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_GameDataMask(  );
	}

	return SP_IOSBridge_GameDataMask(  );
}

int IOSBridge_ImportLooseData( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_ImportLooseData(  );
	}

	return SP_IOSBridge_ImportLooseData(  );
}

int IOSBridge_CampaignModCount( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_CampaignModCount(  );
	}

	return SP_IOSBridge_CampaignModCount(  );
}

const char * IOSBridge_CampaignModDir( int index )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_CampaignModDir( index );
	}

	return SP_IOSBridge_CampaignModDir( index );
}

const char * IOSBridge_CampaignModPak( int index )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_CampaignModPak( index );
	}

	return SP_IOSBridge_CampaignModPak( index );
}

bool IOSBridge_CampaignModInstalled( int index )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_CampaignModInstalled( index );
	}

	return SP_IOSBridge_CampaignModInstalled( index );
}

int IOSBridge_CampaignModMaps( int index )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_CampaignModMaps( index );
	}

	return SP_IOSBridge_CampaignModMaps( index );
}

double IOSBridge_CampaignModMegabytes( int index )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_CampaignModMegabytes( index );
	}

	return SP_IOSBridge_CampaignModMegabytes( index );
}

bool IOSBridge_IsCampaignModDir( const char *dir )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_IsCampaignModDir( dir );
	}

	return SP_IOSBridge_IsCampaignModDir( dir );
}

bool IOSBridge_RussianPaksPresent( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_RussianPaksPresent(  );
	}

	return SP_IOSBridge_RussianPaksPresent(  );
}

bool IOSBridge_RussianPaksEnabled( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_RussianPaksEnabled(  );
	}

	return SP_IOSBridge_RussianPaksEnabled(  );
}

int IOSBridge_SetRussianPaks( bool on )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SetRussianPaks( on );
	}

	return SP_IOSBridge_SetRussianPaks( on );
}

void IOSBridge_SetCvar( const char *name, const char *value )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_SetCvar( name, value );
		return;
	}

	SP_IOSBridge_SetCvar( name, value );
}

const char * IOSBridge_GetCvar( const char *name )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_GetCvar( name );
	}

	return SP_IOSBridge_GetCvar( name );
}

void IOSBridge_ForgetCvar( const char *name )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_ForgetCvar( name );
		return;
	}

	SP_IOSBridge_ForgetCvar( name );
}

void IOSBridge_SetBinding( const char *keyName, const char *action )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_SetBinding( keyName, action );
		return;
	}

	SP_IOSBridge_SetBinding( keyName, action );
}

const char * IOSBridge_GetBinding( const char *keyName )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_GetBinding( keyName );
	}

	return SP_IOSBridge_GetBinding( keyName );
}

void IOSBridge_WriteConfig( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_WriteConfig(  );
		return;
	}

	SP_IOSBridge_WriteConfig(  );
}

void IOSBridge_SetStartupCommand( const char *command )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_SetStartupCommand( command );
		return;
	}

	SP_IOSBridge_SetStartupCommand( command );
}

void IOSBridge_RotateLog( const char *tag )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_RotateLog( tag );
		return;
	}

	SP_IOSBridge_RotateLog( tag );
}

const char * IOSBridge_BuildCommandLine( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_BuildCommandLine(  );
	}

	return SP_IOSBridge_BuildCommandLine(  );
}

void IOSBridge_SetExtraArgs( const char *args )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_SetExtraArgs( args );
		return;
	}

	SP_IOSBridge_SetExtraArgs( args );
}

bool IOSBridge_IsMultiplayer( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_IsMultiplayer(  );
	}

	return SP_IOSBridge_IsMultiplayer(  );
}

void IOSBridge_InitPaths( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_InitPaths(  );
		return;
	}

	SP_IOSBridge_InitPaths(  );
}

void IOSBridge_InitAudioSession( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_InitAudioSession(  );
		return;
	}

	SP_IOSBridge_InitAudioSession(  );
}

void IOSBridge_InitSDLHints( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_InitSDLHints(  );
		return;
	}

	SP_IOSBridge_InitSDLHints(  );
}

void IOSBridge_LogAppend( const char *msg )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_LogAppend( msg );
		return;
	}

	SP_IOSBridge_LogAppend( msg );
}

int IOSBridge_LogSnapshot( char *out, int outSize )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_LogSnapshot( out, outSize );
	}

	return SP_IOSBridge_LogSnapshot( out, outSize );
}

unsigned IOSBridge_LogVersion( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_LogVersion(  );
	}

	return SP_IOSBridge_LogVersion(  );
}

void IOSBridge_SelfTestBegin( const char *title )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_SelfTestBegin( title );
		return;
	}

	SP_IOSBridge_SelfTestBegin( title );
}

void IOSBridge_SelfTestRow( int verdict, const char *group, const char *name, const char *detail )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_SelfTestRow( verdict, group, name, detail );
		return;
	}

	SP_IOSBridge_SelfTestRow( verdict, group, name, detail );
}

void IOSBridge_SelfTestEnd( int passed, int failed, int skipped )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_SelfTestEnd( passed, failed, skipped );
		return;
	}

	SP_IOSBridge_SelfTestEnd( passed, failed, skipped );
}

int IOSBridge_SelfTestSnapshot( char *out, int outSize )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SelfTestSnapshot( out, outSize );
	}

	return SP_IOSBridge_SelfTestSnapshot( out, outSize );
}

int IOSBridge_SelfTestRunning( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SelfTestRunning(  );
	}

	return SP_IOSBridge_SelfTestRunning(  );
}

unsigned IOSBridge_SelfTestVersion( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SelfTestVersion(  );
	}

	return SP_IOSBridge_SelfTestVersion(  );
}

void IOSBridge_SelfTestCounts( int *passed, int *failed, int *skipped )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_SelfTestCounts( passed, failed, skipped );
		return;
	}

	SP_IOSBridge_SelfTestCounts( passed, failed, skipped );
}

void IOSBridge_SelfTestTitle( char *out, int outSize )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_SelfTestTitle( out, outSize );
		return;
	}

	SP_IOSBridge_SelfTestTitle( out, outSize );
}

int IOSBridge_SelfTestLoadStored( char *out, int outSize )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SelfTestLoadStored( out, outSize );
	}

	return SP_IOSBridge_SelfTestLoadStored( out, outSize );
}

void IOSBridge_ExecCommand( const char *command )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_ExecCommand( command );
		return;
	}

	SP_IOSBridge_ExecCommand( command );
}

bool IOSBridge_ServerRunning( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_ServerRunning(  );
	}

	return SP_IOSBridge_ServerRunning(  );
}

void IOSBridge_SetKeepAwake( bool on )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_SetKeepAwake( on );
		return;
	}

	SP_IOSBridge_SetKeepAwake( on );
}

bool IOSBridge_IsKeepAwake( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_IsKeepAwake(  );
	}

	return SP_IOSBridge_IsKeepAwake(  );
}

bool IOSBridge_ScanData( bool rescan )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_ScanData( rescan );
	}

	return SP_IOSBridge_ScanData( rescan );
}

int IOSBridge_DataMaps( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_DataMaps(  );
	}

	return SP_IOSBridge_DataMaps(  );
}

int IOSBridge_DataFiles( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_DataFiles(  );
	}

	return SP_IOSBridge_DataFiles(  );
}

double IOSBridge_DataMegabytes( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_DataMegabytes(  );
	}

	return SP_IOSBridge_DataMegabytes(  );
}

int IOSBridge_SetFileCount( int set )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SetFileCount( set );
	}

	return SP_IOSBridge_SetFileCount( set );
}

const char * IOSBridge_SetFileName( int set, int index )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SetFileName( set, index );
	}

	return SP_IOSBridge_SetFileName( set, index );
}

bool IOSBridge_SetFilePresent( int set, int index )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SetFilePresent( set, index );
	}

	return SP_IOSBridge_SetFilePresent( set, index );
}

bool IOSBridge_SetFileRequired( int set, int index )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SetFileRequired( set, index );
	}

	return SP_IOSBridge_SetFileRequired( set, index );
}

int IOSBridge_SetMaps( int set )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SetMaps( set );
	}

	return SP_IOSBridge_SetMaps( set );
}

int IOSBridge_SetFiles( int set )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SetFiles( set );
	}

	return SP_IOSBridge_SetFiles( set );
}

double IOSBridge_SetMegabytes( int set )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SetMegabytes( set );
	}

	return SP_IOSBridge_SetMegabytes( set );
}

bool IOSBridge_SetIsPlayable( int set )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SetIsPlayable( set );
	}

	return SP_IOSBridge_SetIsPlayable( set );
}

bool IOSBridge_SetIsRecommended( int set )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_SetIsRecommended( set );
	}

	return SP_IOSBridge_SetIsRecommended( set );
}

const char * IOSBridge_EngineVersion( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_IOSBridge_EngineVersion(  );
	}

	return SP_IOSBridge_EngineVersion(  );
}

void IOSBridge_LauncherFinished( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_IOSBridge_LauncherFinished(  );
		return;
	}

	SP_IOSBridge_LauncherFinished(  );
}

bool Sys_IOS_LauncherIsFinished( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		return MP_Sys_IOS_LauncherIsFinished(  );
	}

	return SP_Sys_IOS_LauncherIsFinished(  );
}

void Sys_IOS_LauncherReset( void )
{
	if ( iortcwActiveGame == IORTCW_GAME_MULTIPLAYER ) {
		MP_Sys_IOS_LauncherReset(  );
		return;
	}

	SP_Sys_IOS_LauncherReset(  );
}
